apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-lab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-lab
  template:
    metadata:
      labels:
        app: ai-lab
    spec:
      containers:
      - name: ai-lab-node
        image: This Is Broke
        # command: ["jupyter", "notebook"]
        # args: ["--allow-root", "--NotebookApp.token=03c7f527bad9d22ec5a179b1c8e73117220e3b57ee872958"]
        volumeMounts:
        - mountPath: /workspace
          name: jupyter-data
        - mountPath: /root/.config/wandb
          name: wandb-config
          
      volumes:
      - name: jupyter-data
        hostPath:
          path: /home/zz/video_src/jupyter_mount
          type: DirectoryOrCreate
      - name: wandb-config
        hostPath:
          path: /home/zz/video_src/wandb_mount/wandb/config
          type: DirectoryOrCreate
