apiVersion: v1
kind: Service
metadata:
  name: ai-lab-service
spec:
  selector:
      app: ai-lab
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
    
    # - protocol: TCP
    #   port: 80
    #   targetPort: 8000

  type: LoadBalancer